version: "2"
run:
  modules-download-mode: readonly
linters:
  default: none
  enable:
    - bodyclose
    - govet
    - noctx
  settings:
    govet:
      disable:
        - fieldalignment
        - shadow
        - nilness
        - unusedwrite
      enable-all: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gosec
          - unparam
        path: _test\.go
      - linters:
          - unparam
        path: cmd/
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
